export const InnerGlobalVariables = [
    'letgoContext',
    'utils',
    '$context',
    '$utils',
    'props',
    'localStorage',
    'sessionStorage',
    'console',
    'window',
    'document',
    'navigator',
    'XMLHttpRequest',
    'fetch',
    'canvas',
];
